### ISSUE TITLE
Custom logging setup produces "_pickle.UnpicklingError: invalid load key, '\x00'."

### ISSUE THREAD

**Issue by hugochinchilla** [Bogdanp/dramatiq#185] opened 2019-03-12 11:30 UTC
* [x] Does your title concisely summarize the problem?
* [x] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

Docker image built from library/python:3.7.0

## What version of Dramatiq are you using?

1.5.0

## What did you do?

Ran the worker with `dramatiq -p 1 -t 2 gaia.workers`

## What did you expect would happen?

The worker should pick jobs from the broker and process all of them.

## What happened?

After processing a few jobs the worker stops with the following trace and remains locked (it does not repond to SIGTERM).

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/dramatiq/cli.py", line 259, in watch_logs
    data = event.recv()
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
_pickle.UnpicklingError: invalid load key, '\x00'.
```

### sample code

```python
MAX_MESSAGE_AGE = 4 * 3600 * 1000  # 4 hours in milliseconds


@dramatiq.actor(max_age=MAX_MESSAGE_AGE)
def send_alert_email(template, context, metadata, recipient, notification_uuid):
    sparkpost = SparkPost(settings.SPARKPOST_API_KEY, settings.SPARKPOST_HOST)

    if not settings.ENABLE_SEND_EMAILS:
        # to create a level of stress in phoenix so we can test how it
        # handles load even when not sending real emails to customers
        sparkpost.templates.preview(template, context, draft=False)
    else:
        transmission = sparkpost.transmissions.send(
            recipients=[recipient],
            template=template,
            subject=context['subject'],
            substitution_data=context,
            metadata=metadata,
        )

        # TODO: default session can't be used for multiple countries setup
        with closing(DefaultSession()) as session:
            repo = AlertNotificationRepo(session)
            notification = repo.get(notification_uuid)
            notification.sent_at = datetime.now()
            notification.transmission_id = transmission['id']
            session.add(notification)
```

**Comment by hugochinchilla** [comment] 2019-03-12 14:10
Ok, so I followed the trace and it looks like it's a interference with some custom logging that was in place in my project, as I don't need that any more I will simple remove the code causing the issue.

```python
# use TqdmHandler if the outpout is on a TTY to prevent mixed logger
# and progressbar output
if hasattr(sys.stdout, "isatty") and sys.stdout.isatty():
    from tqdm import tqdm

    class TqdmHandler(logging.StreamHandler):
        def __init__(self):
            logging.StreamHandler.__init__(self)

        def emit(self, record):
            msg = self.format(record)
            tqdm.write(msg)
    console = TqdmHandler()
else:
    console = logging.StreamHandler(sys.stdout)

console.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
console.setFormatter(formatter)
root.addHandler(console)
```

I will not close the issue as this is more of a workarround than a fix.

**Comment by jcass77** [comment] 2019-03-12 14:43
I have also been experiencing this problem intermittently. At first I thought it was because I set
``DRAMATIQ_ENCODER = "dramatiq.encoder.PickleEncoder"`` to use the pickle encoder (see: https://github.com/Bogdanp/dramatiq/issues/17), but I have since switched to JSON and the issue persists.

I also set up a ``LoggingMiddleware`` based on [this Dramatiq pattern for Sentry](https://dramatiq.io/cookbook.html?highlight=sentry#reporting-errors-with-sentry).

It looks pretty vanilla to me so not sure why it would be causing issues:

```
class LoggingMiddleware(dramatiq.Middleware):
    def after_process_message(self, broker, message, *, result=None, exception=None):
        """
        Ensure that message failures (e.g. as a result of timeout or retry limits) are also logged.
        """
        if message.failed and "log_failures" in message._message.options:
            # Log message failures - will also be reported via Sentry if Sentry has been defined as a logging handler
            # with level 'ERROR'.
            logger.error(
                f"Dramatiq task '{message}' (ID: {message._message.message_id}) failed after "
                f"{message._message.options.get('retries', 0)} retries: {exception}."
            )
```

Are there any recommendations for enabling safe logging support for Dramatiq?

**Comment by Bogdanp** [comment] 2019-03-13 18:45
@hugochinchilla and @jcass77, could either of you check if you experience this problem under Python 3.6?  Since is blowing up in standard library code, then this might be some sort of regression in 3.7.

I can sort of see how the `TqdmHandler` could cause these sorts of problems since it presumably writes to std{out,err} which we redirect back into the main process (hence the pickling) and maybe the non-ascii chars are causing issues.

**Comment by Bogdanp** [comment] 2019-03-13 19:07
Would you guys mind testing your code against commit https://github.com/Bogdanp/dramatiq/commit/f37cd91e0dda25a4f58dc9674d4dfc419306440a to see if this still happens?

**Comment by jcass77** [comment] 2019-03-14 13:24
@Bogdanp, I have been running https://github.com/Bogdanp/dramatiq/commit/f37cd91e0dda25a4f58dc9674d4dfc419306440 all afternoon on Python 3.6.7 and have not encountered this problem again.

I think it might be fixed!

**Comment by Bogdanp** [comment] 2019-03-17 11:53
Great! I'm going to close this for now. The change will probably be released within the next couple of weeks. Feel free to re-open the issue if it still occurs for you against the current master branch!

**Closed by Bogdanp** 2019-03-17 11:53 UTC
Labels: bug
