### ISSUE TITLE
(Error) Logging misbehaves when run in Docker

### ISSUE THREAD

**Issue by aberres** [Bogdanp/dramatiq#171] opened 2019-02-18 14:10 UTC
## What OS are you using?

Debian Stretch inside Docker

## What version of Dramatiq are you using?

1.5.0

## What did you do?

Run `dramatiq not.existing; echo $?` in a Docker container.

A simple `docker run --rm -ti python:3.7-stretch /bin/bash` followed by `pip install dramatiq` is the fastest way to get a repro.

## What did you expect would happen?

The worker fails to boot and complains with something along the lines of `ModuleNotFoundError: No module named 'not'`, the return code is always 2.

When running inside an iterm2 Mac zsh shell this is exactly what happens.

## What happened?

When running below docker most of the times the output is completely swallowed. 
Sometimes only `[dramatiq.MainProcess] [INFO] Dramatiq '1.5.0' is booting up.` is printed.

Every 10th or so time the complete expected output can the seen.

The exit code is oscillating between 0 and 2.

I did not have the time yet to investigate but it seems to be related to the logging pipe of the workers.
If I tweak `setup_worker_logging` not to pass the pipe the errors are reported as expected.

I was running into this problem when adding Dramatiq in a Kubernetes setup.
I cannot say yet if there are additional problems when the module can be successfully imported.

**Comment by Bogdanp** [comment] 2019-02-18 15:22
Yeah, something changed in the implementation of `multiprocessing` `Connection` objects in 3.7 which may be the ultimate cause of this. But first, can you make sure you've turned off output buffering? An env var like `PYTHONUNBUFFERED=x` should do the trick.

**Comment by aberres** [comment] 2019-02-18 15:24
Yeps, this one is set.

**Comment by Bogdanp** [comment] 2019-03-13 20:03
@aberres would you mind checking if you still experience this issue against the current `HEAD`?

**Comment by Bogdanp** [comment] 2019-03-17 11:53
I'm going to close this for now. Feel free to re-open the issue if it still occurs for you against the current master branch!

**Comment by aberres** [comment] 2019-03-29 10:16
@Bogdanp, thanks for looking into this.

It seems it is not fixed.

`docker run --rm -ti python:3.7-stretch /bin/bash`
followed by
`pip install https://github.com/Bogdanp/dramatiq/archive/master.zip`
and multiple calls to `dramatiq not.existing; echo $?` still shows only output now and then and mostly finishes with a code of 0 and not 2.

I would reopen the issue but it seems I do not have the rights.

**Comment by Bogdanp** [comment] 2019-03-29 11:14
Thanks for letting me know. I'll try to reproduce this in the coming weeks.

**Comment by parente** [comment] 2019-04-02 18:13
FWIW, I was looking at updating our dramatiq docker images to python 3.7 and wanted to vet if this is a problem for us or not. With `python:3.7-stretch@sha256:fa60a2d97d70f92713e7b8af684756516d6b3e37bf12be49641865ba817305fc` and docker server version 18.09.2, I consistently get exit code 2 and the `ModuleNotFoundError: No module named 'not'` error in the output when running:

```
docker run --rm -ti python:3.7-stretch /bin/bash
pip install dramatiq # Successfully installed dramatiq-1.5.0 prometheus-client-0.2.0
dramatiq not.existing; echo $?
```

I don't doubt this is a problem for the other folks on the thread. Just lending an observation in case it helps narrow down root cause.

**Comment by aberres** [comment] 2019-04-03 07:32
Hmmm. Now it is getting interesting.

The behavior seems to be different with different runtimes.

**Docker engine 18.09.2 on Docker Desktop for Mac**

Here I see the mixed return codes.

```
You should consider upgrading via the 'pip install --upgrade pip' command.
root@0421f15914c4:/# dramatiq not.existing; echo $?
0
root@0421f15914c4:/# dramatiq not.existing; echo $?
0
root@0421f15914c4:/# dramatiq not.existing; echo $?
0
root@0421f15914c4:/# dramatiq not.existing; echo $?
0
root@0421f15914c4:/# dramatiq not.existing; echo $?
0
root@0421f15914c4:/# dramatiq not.existing; echo $?
0
root@0421f15914c4:/# dramatiq not.existing; echo $?
0
root@0421f15914c4:/# dramatiq not.existing; echo $?
[2019-04-03 07:18:29,216] [PID 52] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.5.0' is booting up.
[2019-04-03 07:18:29,219] [PID 55] [MainThread] [dramatiq.WorkerProcess(0)] [ERROR] Failed to import module.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dramatiq/cli.py", line 290, in worker_process
    module, broker = import_broker(args.broker)
  File "/usr/local/lib/python3.7/site-packages/dramatiq/cli.py", line 103, in import_broker
    module = importlib.import_module(modname)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'not'
2
root@0421f15914c4:/# dramatiq not.existing; echo $?
0
```

**Kubernetes on Google Cloud**

The return code is always 2 but sometimes the output just appears partially.

```
root@tmp4-76c96674-wmclp:/# dramatiq not.existing; echo $?
[2019-04-03 07:21:33,350] [PID 84] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.5.0' is booting up.
[2019-04-03 07:21:33,355] [PID 84] [MainThread] [dramatiq.MainProcess] [CRITICAL] Worker with PID 87 exited unexpectedly (code 2). Shutting down...
[2019-04-03 07:21:33,350] [PID 87] [MainThread] [dramatiq.WorkerProcess(0)] [ERROR] Failed to import module.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dramatiq/cli.py", line 290, in worker_process
    module, broker = import_broker(args.broker)
  File "/usr/local/lib/python3.7/site-packages/dramatiq/cli.py", line 103, in import_broker
    module = importlib.import_module(modname)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'not'
2
root@tmp4-76c96674-wmclp:/# dramatiq not.existing; echo $?
[2019-04-03 07:21:34,006] [PID 90] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.5.0' is booting up.
2
root@tmp4-76c96674-wmclp:/# dramatiq not.existing; echo $?
```

**Master on GKE**

Either ot works or sometimes I run into this:

```
# dramatiq not.existing; echo $?
[2019-04-03 07:30:51,447] [PID 319] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.5.0' is booting up.
[2019-04-03 07:30:51,442] [PID 322] [MainThread] [dramatiq.WorkerProcess(0)] [ERROR] Failed to import module.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/dramatiq/cli.py", line 290, in worker_process
    module, broker = import_broker(args.broker)
  File "/usr/local/lib/python3.7/site-packages/dramatiq/cli.py", line 103, in import_broker
    module = importlib.import_module(modname)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'not'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/dramatiq/cli.py", line 259, in watch_logs
    data = event.recv()
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 411, in _recv_bytes
    return self._recv(size)
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
TypeError: an integer is required (got type NoneType)

0
```

**Comment by Bogdanp** [comment] 2020-02-02 10:28
Please let me know if this is still an issue using version 1.8.0 (just released).

**Comment by xmcp123** [comment] 2020-02-21 21:17
> Please let me know if this is still an issue using version 1.8.0 (just released).

I'm running into an extremely similar issue, but running it from subprocess inside a virtual environment.

```
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xmcp/venv/moonshot-tasks/lib/python3.6/site-packages/dramatiq/cli.py", line 297, in watch_logs
    data = event.recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 411, in _recv_bytes
    return self._recv(size)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
TypeError: an integer is required (got type NoneType)
```

I'm just beginning to dig into this issue but this issue was so recent and the only match on the internet, so I figured it was worth letting you guys know.

**Comment by Bogdanp** [comment] 2020-03-29 13:06
I believe this is now fixed on master. I'll cut a release next weekend or the one after that.

**Closed** 2020-03-29 13:06 UTC
Labels: needs investigation

**Comment by yamijuan** [comment] 2020-04-21 18:08
Is this released or planned to be?

**Comment by Bogdanp** [comment] 2020-04-21 18:17
@yamijuan I haven't had a chance to do it yet, but it should come out soon.
