### ISSUE TITLE
dramatiq should work with python >= 3.4.

### ISSUE THREAD

**Issue by jssuzanne** [Bogdanp/dramatiq#7] opened 2017-11-09 17:12 UTC
Hi,

Actually dramatiq works only with python 3.6 and 3.7a. the linux distribution haven't got theses versions of python. Why don't you keep the capability to use use Python 3.4 and highter

**Comment by jssuzanne** [comment] 2017-11-15 12:54
I have started, the implementation in the [branch](https://github.com/jssuzanne/dramatiq).

For python 3.5, it is easy I have juste replaced `print(f"{}")` by `print("%s" % ...)` .
Python 3.4 is harder, yield from does not work with pip install, I removed it in **setup.py**. the `return self._replace(**attributes, options=options)` is forbidden, I replaced it. I waiting travis, but some test seem faild.

I don't know if the fix will be easy. 

Do you want a PR for Python3.5 alone or you would like to wait both.

**Comment by Bogdanp** [comment] 2017-11-16 07:27
Yeah, let's do it with 3.5 first. Don't forget to add yourself to the contributors file (people often do :P)!

**Comment by Bogdanp** [comment] 2017-11-17 10:21
The 3.4 branch is blocked by this CPython issue: https://bugs.python.org/msg306427

**Comment by Bogdanp** [comment] 2017-11-17 11:00
Since it sounds like the issue is not going to be fixed in 3.4, I'm not going to exert any more effort into supporting that version.

**Closed by Bogdanp** 2017-11-17 11:00 UTC
Labels: enhancement

**Comment by jssuzanne** [comment] 2017-11-17 13:31
You are right, python 3.5 is a good step, enough for now

**Comment by Bogdanp** [comment] 2017-11-17 13:34
Yup! I forgot to mention: 0.13.1 is released with support for 3.5 :D

**Comment by jssuzanne** [comment] 2017-11-17 15:30
I saw it ;)
