### ISSUE TITLE
How i can limit worker to receive one message from broker while it done it?

### ISSUE THREAD

**Issue by AduchiMergen** [Bogdanp/dramatiq#283] opened 2020-03-13 08:25 UTC
i need this case:
1) receive one message from broker
2) execute actor
3) go to 1

How i can implement it with dramatiq?

**Comment by takhs91** [comment] 2020-03-16 11:42
Possibly duplicate of https://github.com/Bogdanp/dramatiq/issues/183 ?

**Comment by Bogdanp** [comment] 2020-03-18 07:52
It's hard to tell exactly what you're asking based on the description, but @takhs91 is probably right and you want to modify the queue prefetch parameter.

**Closed by Bogdanp** 2020-03-18 07:52 UTC
